### ISSUE TITLE
NICK Parse error

### ISSUE THREAD

**Issue by msmosso** [gf3/IRC-js#15]
I got this issue:

[Tue, 21 Dec 2010 23:16:33 GMT] ERROR      [ERROR] Failed parsing ':\1!~felipe@unaffiliated/ecl NICK :\0'
/home/msmosso/rhythm/modules/Jerk/node_modules/.npm/irc-js/0.2.11/package/lib/irc.js:145
          throw err
          ^
Error: treeWalker: parse failed: 0 parse already failed
    at err (/home/msmosso/rhythm/modules/Jerk/node_modules/.npm/irc-js/0.2.11/package/node_modules/PanPG/PanPG_util.js:157:9)
    at Object.treeWalker (/home/msmosso/rhythm/modules/Jerk/node_modules/.npm/irc-js/0.2.11/package/node_modules/PanPG/PanPG_util.js:104:10)
    at Object.walk (/home/msmosso/rhythm/modules/Jerk/node_modules/.npm/irc-js/0.2.11/package/lib/walker.js:36:21)
    at Object.compile (/home/msmosso/rhythm/modules/Jerk/node_modules/.npm/irc-js/0.2.11/package/lib/compiler.js:8:17)
    at IRC.parseMessage (/home/msmosso/rhythm/modules/Jerk/node_modules/.npm/irc-js/0.2.11/package/lib/irc.js:125:28)
    at Stream.<anonymous> (native)
    at Stream.emit (events:27:15)
    at IOWatcher.callback (net:484:33)
    at node.js:773:9

**Comment by andoma** [comment]
I've seen the same error. backslashes are probably the root of evil

**Comment by gf3** [comment]
Sorry, I never received an email about this issue!

**Comment by gf3** [comment]
![BAM](http://f.cl.ly/items/0p431d0m011c2A2I1e2q/Screen%20shot%202011-01-12%20at%2010.48.06%20AM.png)

Fixed in `0.2.13` (which is pushed).

**Comment by andoma** [comment]
Thanks, will try it out later this week
