### ISSUE TITLE
Parse Error with specific User Names

### ISSUE THREAD

**Issue by davglass** [gf3/IRC-js#18]
Filed this under Jerk too:
https://github.com/gf3/Jerk/issues/issue/6

If I have a bot in a room and someone with a username like this: davglass\test` joins, it throws a syntax error:

[Thu, 20 Jan 2011 15:31:24 GMT] ERROR      [ERROR] Failed parsing ':davglass\test`!~davglass@173-27-206-95.client.mchsi.com JOIN :#yui'

/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/irc.js:136
          throw err
          ^
Error: treeWalker: parse failed: 0 parse already failed
    at err (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/node_modules/PanPG/PanPG_util.js:157:9)
    at Object.treeWalker (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/node_modules/PanPG/PanPG_util.js:104:10)
    at Object.walk (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/walker.js:36:21)
    at Object.compile (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/compiler.js:8:17)
    at IRC.parseMessage (/usr/local/lib/node/.npm/jerk/1.1.1/package/node_modules/.npm/irc-js/0.2.11/package/lib/irc.js:116:28)
    at Stream.<anonymous> (native)
    at Stream.emit (events:27:15)
    at IOWatcher.callback (net:484:33)
    at node.js:773:9

I can stop this by setting options.log: false in the config, but that doesn't help me since I like my logging.

**Comment by gf3** [comment]
Hey there, looks like you're using an old version of Jerk which is in turn using an old version of IRC-js (`0.2.11`), this has actually been fixed recently (`0.2.13`).

I added a test case with your example just to be sure :)

fc7d0c0072f6fd5c34ab8847956ac8e8cebf62ad

**Comment by davglass** [comment]
I'm using the latest npm package:
jerk@1.0.0   Stupidly simple IRC bots in Javascript.    =gf3 remote
jerk@1.1.1   Stupidly simple IRC bots in Javascript.    =gf3 active installed latest remote

Can you publish an updated version so I can get the fix?

**Comment by gf3** [comment]
Sorry! I've done so, Jerk `1.1.2` is available.

**Comment by davglass** [comment]
Thanks, works like a charm now!
