### ISSUE TITLE
Empty string causes exception in privmsg

### ISSUE THREAD

**Issue by broofa** [gf3/IRC-js#29]
When passing "" (empty string) to message.say(), I get this ...

Cannot read property 'length' of null TypeError: Cannot read property 'length' of null
    at IRC.privmsg (/Users/chat/projects/facebot/node_modules/jerk/node_modules/irc-js/lib/irc.js:669:38)
    at _privmsg_protected (/Users/chat/projects/facebot/node_modules/jerk/lib/jerk.js:121:16)
    at Object.say (native)
    at Object.action (/Users/chat/projects/facebot/plugins/say.js:46:17)
    at _handleMessage (/Users/chat/projects/facebot/facebot.js:130:19)
    at Array.1 (/Users/chat/projects/facebot/facebot.js:180:7)
    at Jerk._receive_message (/Users/chat/projects/facebot/node_modules/jerk/lib/jerk.js:90:22)
    at IRC.<anonymous> (native)
    at EventEmitter.<anonymous> (native)
    at EventEmitter.emit (events.js:64:17)

**Comment by gf3** [comment]
Thanks!
