### ISSUE TITLE
print() has moved...

### ISSUE THREAD

**Issue by daralthus** [gf3/IRC-js#3]
Hi, I just updated to node 0.1.102 and I got the following error when I run a previously working code:
node.js:11
    throw new Error(reason)
          ^
Error: print() has moved. Use require('sys') to bring it back.
    at node.js:11:11
    at Function.bind (native)
    at new IRC (/home/balkezeskifli/src/au/IRC-js/lib/irc.js:142:5)
    at Object.<anonymous> (/home/balkezeskifli/src/au/multi/app.js:24:18)
    at Module._compile (module:423:23)
    at Module._loadScriptSync (module:433:8)
    at Module.loadSync (module:306:10)
    at loadModule (module:251:12)
    at require (module:374:12)
    at requireApp (/usr/local/bin/connect:323:15)

Thank's for any ideas or pathes!

**Comment by gf3** [comment]
Cool, I'll look into updating IRC-js, thanks.

**Comment by daralthus** [comment]
Great! It seams the problem is with utools bind(). I tried using wu.js bind() and it works so that should be the problem.
Thank's again!

**Comment by gf3** [comment]
Looks like V8 now has a native `Function#bind` :)

**Comment by gf3** [comment]
This is actually a V8/node issue, should be cleaned up soon.

**Comment by gf3** [comment]
Fixed in ry/node@b2a2bb736b01dfcd909d2c9087135bc6cb3e2e15
